### ISSUE TITLE
Make signing work

### ISSUE THREAD

**Issue by pharesim** [pharesim/steemsign#1]
I'm stuck in the signing process. All those buffers grow over my head.

Creating a ByteBuffer at https://github.com/pharesim/steemsign/blob/master/steemsign.js#L96 doesn't work, ByteBuffer is not defined. I'm also not sure if L94 is good (original here: https://github.com/steemit/steemit.com/blob/master/shared/chain/transactions.js#L50)

After that's solved: convert the remaining buffers below, find an ecdsa lib or extract the functions from the node dependency, create a signed "transfer" operation.

The following sources have been used to reach the current state:
https://github.com/svk31/steemjs-lib/blob/master/lib/ecc/src/signature.js#L62 (and more)
https://github.com/steemit/steemit.com/blob/master/shared/chain/transactions.js#L54
https://github.com/steemit/steemit.com/blob/master/shared/serializer/src/serializer.js#L190

**Comment by pharesim** [comment]
Bounty: https://www.bountysource.com/issues/36546628-make-signing-work

**Comment by pharesim** [comment]
More bounty: https://steemit.com/steem/@pharesim/bounty-for-completion-of-native-javascript-steem-signer

**Comment by willbanks** [comment]
Yep I'm working on it.  Just wondering about the approach being taken.  You have a dozen different buffer types you're dealing with, not all of them have the same bitwidth or endianess.

I am trying to bring myself up to speed on the steemit code, but for some reason the core dev team seems to be allergic to commenting their code. ;)

**Comment by willbanks** [comment]
Also, when I'm done you can keep the bountysource bounty, I don't like doxing myself.  Seems like every day one of these companies gets compromised and at this point in my life I have more years of "free credit monitoring" left, than I have years of life remaining. 
The SBD from your posting will be enough.

**Comment by willbanks** [comment]
Where are you getting steem.min.js from?  I mean specifically where did it come from or what did you use to generate it?

**Comment by pharesim** [comment]
The buffers are all coming from steemit/steemjs-lib, the different types are one of the reasons this issue exists ;-)

steem.min.js is this one: https://github.com/pharesim/steemjs

**Comment by willbanks** [comment]
@pharesim Understood and thanks, I think this may be more of a build system issue than anything.

There is a TON of cruft in the steemit code which is surprising for something so new, but I think part of it is they are trying to do this with react.  Lots of "babel" cruft in their code.

For the time being I deminified steem.min.js I'll leave it as is and let you fix that.
Right now I'm seeing if I can build this with just the minimum deps and something like browserify because that feels like the most direct way to solve this.  

Can you whip out a test case for me please?  I need to see how this is supposed to be called.  Nothing fancy is required just something showing how you want calling semantics and preferably a known input/output vector I can check against.
I don't need any big framework, simpler is better right now.

**Comment by willbanks** [comment]
Oh wait down at the bottom of steemsign.is something that looks like a test case.  Is that the test we're working against?

**Comment by willbanks** [comment]
@pharesim: Ok so svk uploaded a browserifiable version while I was in the middle of this bounty.
The dependency tree to make this work is roughly the same as his. Just wondering if you're still trying to go ultra light weight or if you want me to adapt your script to call into his stuff and thereby save the maintenance headaches later.

I'm thinking if nothing else we can use this as a base and just extract the particular bits you want, but I don't see it getting much smaller TBH.

Your bounty though, so you let me know what you want me to do.

**Comment by willbanks** [comment]
Alright, so code is complete and test cases are passing.  There is a tiny amount of code cleanup remaining but substantially everything is ready and sitting in the steembots fork of this repo if you want to do a pull of that and make sure it's usable.
We do appear to be code complete at this time though.
If you want to send the SBD to me once you've had a chance to check it I'll make sure @jtault gets his half of that and I'll release the claim on the bounty at bounty source so he can collect that too.

**Comment by willbanks** [comment]
Ok small update, ECC lib is missing some bits, but they are getting pushed up here very soon.  Give it just a bit because I didn't realize he was working in the same directory and we now have a merge conflict.  But we'll get it resolved soon.

**Comment by pharesim** [comment]
solution now: use steem.js :)
